#!/usr/bin/env sh
# Get battery percentage from acpi

charge="$(acpi -b 2>/dev/null | cut -d " " -f4 | sed s/%.*$//)"

if  [ "`acpi -a 2>/dev/null | grep 'on'`"  != '' ]; then
    charge+="%(charging)"
elif [ "${charge}" -lt 20 ] ; then
    charge+="% < < < WARNING! > > > "
else
    charge+="%"
fi

echo -e "${charge}"
