#!/usr/bin/env sh
# Returns the branchname of the current git repository if it exists.
git branch 2>/dev/null | grep \* | python -c 'import sys; x=sys.stdin.read().rstrip().replace("* ", "*")' 2>/dev/null
