#!/usr/bin/env sh
# Take a screenshot and save to a sensible location.
help='
Screenshot

Usage:
    screenshot [ -h | --help ]
    screenshot <image>
    note : image name must end in .png
'

# Make a screenshot directory if it does not exist
mkdir -p ~/screenshots

if [ "${1}" == '-h' ] || [ "${1}" == '--help' ] ; then
    echo "$help"
    exit 1
elif [ "${1}" != '' ]  ; then
    filename="${1}"
else
    filename="${HOME}/screenshots/screen-capture%Y%m%dT%H%M.png"
fi

# Note scrot must 
scrot "${filename}"

