#!/usr/bin/env sh
# Get the currently connected network profile(s).
netctl list | grep '*' | python -c 'from sys import stdin; x=stdin.read().split(" "); print(x[1] if len(x) >= 2 else "-")' 2>/dev/null

